version: '3'

services:
  node:
    image: originresearch/infernet-node:0.0.1
    ports:
      - "0.0.0.0:5000:5000"
    volumes:
      - type: bind
        source: ./config.json
        target: /app/config.json
      - node-logs:/logs
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - network
    restart:
      on-failure
    extra_hosts:
      - "host.docker.internal:host-gateway"
    stop_grace_period: 1m

  fluentbit:
    image: fluent/fluent-bit:latest
    ports:
      - "24224:24224"
    environment:
      - FLUENTBIT_CONFIG_PATH=/fluent-bit/etc/fluent-bit.conf
    volumes:
      - ./fluent-bit.conf:/fluent-bit/etc/fluent-bit.conf
      - /var/log:/var/log:ro
    networks:
      - network
    restart:
      on-failure

networks:
  network:


volumes:
  node-logs:
